### PR TITLE
Remove RejectConnection detour + unused signature

### LINKED ISSUE #27: Server reports maxplayers -1 on rare occasions
This is pretty rare, maybe 1 or 2 times a week. But there are times where the player count is 1 less than max players until someone disconnects. For example it will show 31/32 in the server browser, but players cannot join with the standard server full message.

~~This only started happening after the x64 update.~~ I have confirmed with another host that uses the connect ext and they also have the problem, it goes away when the ext is removed.

Something to note, we do have sourcetv running all the time.

### LINKED ISSUE #32: Last TF2 update makes connect crash
As of TF2 newest update, connect seems to be causing random crash. It's highly probably some engine structures have changed

https://crash.limetech.org/brg5u3h7to43

### PR DESCRIPTION
**Pull request by Kenzzer**
- Removed `RejectConnection` detour, this should fix #27 
- Call `RejectConnection` with the correct calling convention, this should fix #32
- Removed `CBaseClient__SetSteamID` this signature is completely unused

### CODE REVIEW

File: extension/extension.cpp [hunk 1]
```diff
@@ -95,25 +93,70 @@ class CSteam3Server
...
+		u.details.addr = addr;
+#ifdef __linux__
+		u.details.adjustor = 0;
+#endif
+		return (((FEmptyClass*)ptrThis)->*u.ptr)(args...);
+	}
+};
 
+CDetour* detourCBaseServer__ConnectClient = nullptr;
 bool g_bEndAuthSessionOnRejectConnection = false;
```
Comment (asherkin) [inline extension/extension.cpp:160]: This is unused now, right?

File: extension/extension.cpp [hunk 2]
```diff
@@ -277,18 +258,11 @@ DETOUR_DECL_MEMBER9(CBaseServer__ConnectClient, IClient*, netadr_t&, address, in
...
-
-DETOUR_DECL_MEMBER3(CBaseServer__RejectConnection, void, netadr_t &, address, int, iClientChallenge, const char *, pchReason)
-{
-	if (g_bEndAuthSessionOnRejectConnection)
+	if (client == nullptr)
 	{
-		EndAuthSession(g_lastClientSteamID);
-		g_bEndAuthSessionOnRejectConnection = false;
+		g_pEndAuthSession(steamGameServer, g_lastClientSteamID);
 	}
```
Comment (asherkin) [inline extension/extension.cpp:264]: Does this mean the engine now reliably calls EndAuthSession in RejectConnection? Otherwise this risks leaving the auth session open. If it was reliably called inside, I'd have expected the -1 players issue to be consistent rather than a rare occurrence.

Comment (Kenzzer) [reply extension/extension.cpp:264]: The issue with -1 players specifically shows up when SourceTV is enabled (#27) because connect calls `EndAuthSession` on `g_lastClientSteamID` when a client gets rejected from the SourceTV server which is 100% wrong

And yes the engine reliably ends the authsession if a client gets rejected. The auth session is meant to stay opened for as long as the player is connected to the server, hence why we only close it if a nullptr got returned.

Comment (asherkin) [reply extension/extension.cpp:264]: SourceTV being the issue there makes sense, good find, likely caused by the refactoring that moved away from the check connection type hook I guess. 

Yes, but, we're starting the auth session earlier than the engine normally does. Originally, we had to manually invoke EndAuthSession ourselves if the connection was rejected between our BeginAuthSession and where the engine would have called it itself - or it would be left open until the player tried to join another server.

Comment (asherkin) [reply extension/extension.cpp:263]: Aye, but that is how the code was before e1237c1b38de26829ed02cff20477689e4f7e1c9 too - and it wasn't enough.

The problematic order being:
1. Connect's `CBaseServer::ConnectClient` hook started
2. Connect called `BeginAuthSession` for the client
3. Connect accepted the connection and called the real `CBaseServer::ConnectClient`
4. The engine/game rejected the connection
5. `RejectConnection` was called and the client disconnected - but the engine never called `EndAuthSession`
6. The client stayed in the server info players list until they joined another server

I can totally believe this issue went away when the engine was refactored and `CheckChallengeType` was removed, just want to ensure it's sufficiently covered rather than just a return to the "obvious" implementation because *we're* cleaning up enough.

Comment (Kenzzer) [reply extension/extension.cpp:263]: Sorry but I don't understand the issue, that scenario can't happen. If the server rejected the client we will know because nullptr is returned which we check and end the auth session for.

Best case scenario end auth session is called twice, once by the engine and once by us. Worst case scenario its only called by us.

Comment (Kenzzer) [reply extension/extension.cpp:263]: If we really want to be safe we can check if the suppress auth boolean has been flipped. If it hasn't been then we end auth session, because the server never tried to auth the ticket and therefore isn't ending the auth session either.

Comment (asherkin) [reply extension/extension.cpp:263]: > Sorry but I don't understand the issue, that scenario can't happen. If the server rejected the client we will know because nullptr is returned which we check and end the auth session for.
> 
> Best case scenario end auth session is called twice, once by the engine and once by us. Worst case scenario its only called by us.

That works for me 👍

**Review by asherkin — APPROVED** [review]

**Comment by sapphonie** [comment]
LGTM
